### ISSUE TITLE
False positive when Using font-awesomme-rails

### ISSUE THREAD

**Issue by Undistraction** [schneems/sprockets_better_errors#10]
I'm guessing this is related to [#5](https://github.com/schneems/sprockets_better_errors/issues/5), but posting here anyway.

I'm using [font-swesome-rails](https://github.com/bokmann/font-awesome-rails), and although everything is working fine in development and on staging (on Heroku), I'm getting the following error in development:

```
Asset depends on 'fontawesome-webfont.eot' to generate properly but has not declared the dependency
Please add: `//= depend_on_asset "fontawesome-webfont.eot"` to '/path/to/app/assets/stylesheets/application.css.scss'
```

**Comment by schneems** [comment]
What is the backtrace and can you give me the line it references in `application.css.scss`? If not, maybe you can give me a super simple sample app that demonstrates this breakage?

**Comment by jackson-sandland** [comment]
I am having this exact same problem.

**Comment by schneems** [comment]
@jackson-sandland What is the backtrace and can you give me the line it references in `application.css.scss`? If not, maybe you can give me a super simple sample app that demonstrates this breakage?

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
