### ISSUE TITLE
Asset depends_on error with compas_rails sprite generation

### ISSUE THREAD

**Issue by otty** [schneems/sprockets_better_errors#12]
Hi,

i think this is a bug. When using compass's automatic sprite gen (http://compass-style.org/help/tutorials/spriting/) the error 

```
Asset depends on 'icons-s0d55df5d8a.png' to generate properly but has not declared the dependency 
Please add: `//= depend_on_asset "icons-s0d55df5d8a.png"` to... 
```

is always raised when setting

```
config.assets.raise_production_errors = true
```

But starting the production environment does not raise any errors when running

```
rake asset:precompile
```

is there a workaround except disabling `assets.raise_production_errors` ?

**Comment by schneems** [comment]
If you're referencing an asset from within another asset you need the `depend_on_asset` directive or cached assets will not function correctly. If you are generating asset names through a tool you should also generate the `depend_on_asset` lines as well.

**Comment by faelsoto** [comment]
I'm with the same issue, compass generates a sprite file with its unique digest. I just can't simply list them all and update it whenever something has changed.

Is there a workaround for this? Something like `require_tree` for `depend_on_asset` would be nice, but I can't find nothing on sprocket's side.

Thanks.

**Comment by schneems** [comment]
@faelsoto not that i know of, opening up a ticket on sprockets and listing the behavior you would like to achieve would be a good place to start

**Comment by robertwbradford** [comment]
Has anyone found a solution for this?

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
