### ISSUE TITLE
Dynamic assets with asset_path

### ISSUE THREAD

**Issue by gjaldon** [schneems/sprockets_better_errors#13]
When I do `config.assets.raise_production_errors = true` in development, errors are raised for my code that dynamically generates assets inside a coffee.erb file.

I have code that looks like this where I want to call images through asset_path dynamically since there are a lot of them.
`"<%= asset_path('#{fileType}.png') %>"`

However, I get this error:
`Asset not present: could not find '#{fileType}.png' in any asset directory`

**Comment by glebm** [comment]
Strings in single quotes do not interpolate in ruby. You can use `"` instead: `"#{..}.png"`.
More on strings in ruby:
- http://en.wikibooks.org/wiki/Ruby_Programming/Strings
- http://en.wikibooks.org/wiki/Ruby_Programming/Alternate_quotes

**Comment by gjaldon** [comment]
I'm interpolating a string in coffeescript and not in Ruby. That's why I used single quotes inside erb but double quotes outside of it. `fileType` is a coffeescript variable.

**Comment by glebm** [comment]
`erb` extension, therefore this is [eRuby](http://en.wikipedia.org/wiki/ERuby).  ruby `<%=%>` block has no access to the dynamic JS context.

**Comment by gjaldon** [comment]
It works as I expected in development but not in production.

**Comment by schneems** [comment]
> It works as I expected in development but not in production.

You will need to tell us how you expected it to work, then how it behaved in development and then in production.

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
