### ISSUE TITLE
Raising false errors on public directory images

### ISSUE THREAD

**Issue by ykessler** [schneems/sprockets_better_errors#16]
After installing this gem, we're getting errors on the following:

`<img src="<%= asset_path('images/video/thumbs/test.png') %>`

Raises:  

>    Sprockets::Rails::Helper::AssetNotPresentError in Home#home
>    Asset not present: could not find 'images/video/thumbs/test.png' in any asset directory

Yet it's a valid path and serves up fine at:

http://localhost:7000/images/video/thumbs/test.png

**Comment by schneems** [comment]
If you run this in production you'll get an error. If the image is in public, you shouldn't be using `asset_path` helper, instead just hard-coding the path in there. Try removing the gem, running rake `assets:precompile` and starting the server locally all using `RAILS_ENV=production`.
