### ISSUE TITLE
Incompatible with sprockets-rails 2.1.1

### ISSUE THREAD

**Issue by davetron5000** [schneems/sprockets_better_errors#18]
Seems that `check_errors_for`'s signature changes to require two arguments.

https://github.com/rails/sprockets-rails/commit/270d0dfa21e8135ad3070bf4e5f1ca5741510ec8

Personally, that should've been considered a breaking change, because `protected` methods are part of the public interface in my opinion.

Exception:

```
sprockets_better_errors (0.0.4) lib/sprockets_better_errors/sprockets_rails_helper.rb:79:in `check_errors_for'
sprockets-rails (2.1.3) lib/sprockets/rails/helper.rb:156:in `block in stylesheet_link_tag'
sprockets-rails (2.1.3) lib/sprockets/rails/helper.rb:155:in `map'
sprockets-rails (2.1.3) lib/sprockets/rails/helper.rb:155:in `stylesheet_link_tag'
sprockets_better_errors (0.0.4) lib/sprockets_better_errors/sprockets_rails_helper.rb:74:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:6:in `_app_views_layouts_application_html_erb__2570025709121141844_70259046937360'
actionview (4.1.0) lib/action_view/template.rb:145:in `block in render'
```

Sorry I don't have a PR for this—I think it would be simple to do, but I don't have time right this moment

**Comment by schneems** [comment]
sprockets_better_errors shouldn't be used with 4.1 as it was merged in, entirely. I didn't do a proper version declaration in 0.0.4 but it's fixed in 0.0.5 https://github.com/schneems/sprockets_better_errors/blob/master/sprockets_better_errors.gemspec#L32 maybe I should also restrict the sprockets-rails version as well...

**Comment by davetron5000** [comment]
Ah, OK.  This happened when I updated to 4.1, so that makes sense.  Sorry for the bother…

**Comment by monfresh** [comment]
@schneems, yes you should restrict the sprockets-rails version as well because this will break somewhere between Rails 4.0.4 and 4.0.8 when they changed the dependency on sprockets-rails from `~> 2.0.0` to `~> 2.0`. See issue #22 that I just opened.

**Comment by schneems** [comment]
This is on master https://github.com/schneems/sprockets_better_errors/blob/master/sprockets_better_errors.gemspec#L31 I haven't had a chance to release a new gem, even then it doesn't show up unless you bundle update which seems kinda lame, but better than nothing. Sorry for slow response, thanks for the comments.
