### ISSUE TITLE
Doesn't work well with filename.min.js files

### ISSUE THREAD

**Issue by cymen** [schneems/sprockets_better_errors#19]
I get an error with this suggestion:

```
config.assets.precompile += %w( honeybadger.min )
```

But I already have this:

```
config.assets.precompile += %w( honeybadger.min.js )
```

And I need to it to have `.js` to work correctly with another gem that is syncing assets. Any thoughts?

**Comment by schneems** [comment]
What line in your code is causing that error? i.e. `asset_path "honeybadger.min.js"`? I would like to take a closer look a this.

**Comment by cymen** [comment]
This line:

``` ruby
config.assets.precompile += %w( honeybadger.min.js )
```

**Comment by schneems** [comment]
I see that line, i'm referring to the one that is raising the error. This would either come from an asset like `application.css.erb` or from your view.

**Comment by cymen** [comment]
``` ruby
<%= javascript_include_tag 'honeybadger.min' %>
```

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
