### ISSUE TITLE
Obsoleted by rails 4.0.6

### ISSUE THREAD

**Issue by jaredbeck** [schneems/sprockets_better_errors#20]
### Rails 4.0.6 updated its dependency on sprockets-rails

``` diff
- sprockets-rails ~> 2.0.0 # rails 4.0.5
+ sprockets-rails ~> 2.0 # rails 4.0.6
```

As a result, 4.0.6 will use sprockets-rails 2.1.x

As we already know, [sprockets_better_errors is obsoleted by sprockets-rails >= 2.1](https://github.com/rails/sprockets-rails/pull/96#issuecomment-39873564), and also seems to be incompatible.
### Potentially Incompatible?

Using sprockets-rails 2.1.3 and sprockets_better_errors 0.0.5 I get the following error:

```
     ActionView::Template::Error:
       wrong number of arguments (2 for 1)
         (in /Users/jared/REDACTED/facebook.js.erb)
     # /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sprockets_better_errors-0.0.5/lib/sprockets_better_errors/sprockets_rails_helper.rb:71:in `check_errors_for'
     # /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/helper.rb:80:in `asset_path'
     # /Users/jared/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/helper.rb:89:in `asset_url'
     # REDACTED/facebook.js.erb:90:in `block in singleton class'
```
### Solution?

Maybe sprockets_better_errors should depend on sprockets-rails < 2.1 instead of the current dependency: rails < 4.1.

**Comment by schneems** [comment]
It would be better to peg this to sprockets-rails instead of to https://github.com/schneems/sprockets_better_errors/blob/master/sprockets_better_errors.gemspec#L32.

Could you work up a PR here?

**Comment by jaredbeck** [comment]
Sure.  I'll close this.  See PR https://github.com/schneems/sprockets_better_errors/pull/21
