### ISSUE TITLE
vendored css and js must be included with the file extension (?)

### ISSUE THREAD

**Issue by timdiggins** [schneems/sprockets_better_errors#26]
I'm writing this as much as a note for others (I'm not sure if it's worth fixing as there's a really easy workaround, and this gem is obsoleted by rails 4.1) 

It appears (based on my setup, YMMV) if you have an asset in vendor/assets (either in your project path or provided by a gem) then you need to refer to the file including the extension (officially [the extension is optional](http://apidock.com/rails/ActionView/Helpers/AssetTagHelper/javascript_include_tag)) when you include it, (non vendored css/js are working fine) e.g:

```
    = stylesheet_link_tag 'jquery.css'
    = javascript_include_tag('jquery.js')
```

Otherwise you will get a false AssetFilteredError.

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
