### ISSUE TITLE
ActionView::Template::Error (wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by poc7667** [schneems/sprockets_better_errors#28]
After upgrading to Rails 4.2.0 add with the following gem,

I keep getting this error `ActionView::Template::Error (wrong number of arguments (2 for 1)`
when precompile my project, I fixed it with removing `sprockets_better_errors`
- bootstrap-sass (3.1.1.1)
- sass (3.4.13)
- sass-rails (5.0.1)

**Comment by schneems** [comment]
sprockets_better_errors is incompatible with Rails 4.2.0 as the changes were merged in. This is expected.
