### ISSUE TITLE
Optionally ignore missing dependency declarations from external gems

### ISSUE THREAD

**Issue by luisalima** [schneems/sprockets_better_errors#5]
Dear @schneems ,

Thank you for an awesome gem!

I was using it for the first time today and I got `Sprockets::Rails::Helper::DependencyError`s on the `jquery-ui-rails` gem. 

While discussing the fix (see the conversation [here](https://github.com/joliss/jquery-ui-rails/pull/59)), it became apparent to the repository maintainer that, in this particular case, this wouldn't be a cause for concern.

I would like to ask you whether there is a way (or whether you are considering a way) of configuring `sprockets_better_errors` to ignore certain external dependencies?

**Comment by irobayna** [comment]
:+1:

**Comment by schneems** [comment]
Do you know if it is possible to tell if an asset is coming from a Gem? Adding a place to declare files to ignore is just as much work as adding in the checks. You can fork the Gem and add in your own checks though this is less than ideal. 

Given the conversation I could see wanting to disable all asset Gem checks and I could add a flag in that does that, I just don't know if it's possible to see if an asset is in a gem or not.

**Comment by luisalima** [comment]
I see your point, now that I think about it, I also have no clue on how to determine whether an asset is in an external gem or not.

Perhaps a good middle ground would be to ignore an asset based on a list of regular expressions (and match them on the full path+name so that people can just configure them anyway they want. That way we could just create the regular expressions for the external offending gems :), since I don't want to disable your checks, I find them amazingly useful. I can take a look at how you did things and have a go at it if you need help. What do you think?

**Comment by masterkain** [comment]
I'm having a bit of trouble understanding what's going on with the `bootstrap-sass` gem.

```
Asset depends on 'bootstrap/glyphicons-halflings-regular.eot' to generate properly but has not declared the dependency
Please add: `//= depend_on_asset "bootstrap/glyphicons-halflings-regular.eot"` to '/myapp/rails/app/assets/stylesheets/hipchat.css.scss'
  (in /myapp/rails/app/assets/stylesheets/hipchat.css.scss)
/gems/sprockets_better_errors-0.0.4/lib/sprockets_better_errors/sprockets_rails_helper.rb:17:in `check_dependencies!'
/gems/sprockets_better_errors-0.0.4/lib/sprockets_better_errors/sprockets_rails_helper.rb:22:in `compute_asset_path'
/bundler/gems/rails-2612248f8c7f/actionpack/lib/action_view/helpers/asset_url_helper.rb:132:in `asset_path'
/bundler/gems/rails-2612248f8c7f/actionpack/lib/action_view/helpers/asset_url_helper.rb:343:in `font_path'
/gems/bootstrap-sass-3.0.3.0/lib/bootstrap-sass/sass_functions.rb:17:in `twbs_asset_path'
/gems/bootstrap-sass-3.0.3.0/lib/bootstrap-sass/sass_functions.rb:6:in `twbs_font_path'
```

https://github.com/twbs/bootstrap-sass/blob/master/vendor/assets/stylesheets/bootstrap/_glyphicons.scss#L11

Should this gem declare those assets?

```
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.eot"
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.woff"
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.ttf"
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.svg"
```

Apparently there's no .erb files involved, but I still don't fully grasp the concept since `sprockets_better_errors` has been giving me those kind of exceptions on pretty much any extra asset (image, fonts, flash).

**Comment by luisalima** [comment]
Hi @masterkain , this is not just the `sprockets_better_error` gem: Rails master also raises the errors when the dependencies are not properly declared (see [this PR](https://github.com/rails/sprockets-rails/pull/96)).

`_glyphicons.scss` should be renamed to `_glyphicons.scss.erb` and declare the missing assets. What I've been doing with most gems I'm using is to fork them, make the changes and then do a pull request. But you can use the feature introduced by @schneems in the [pull request referenced above](https://github.com/rails/sprockets-rails/pull/100) to skip asset dependency checks in order to continue developing without restrictions (however, not sure whether that's a good idea...)

**Comment by schneems** [comment]
@luisalima i'm curious why there is a need to add an `erb` to the end of the file? I'm also unsure what is triggering the failure as this failure should only come from `erb` files (not the other way around)...

**Comment by luisalima** [comment]
@schneems in the meanwhile I learned that .`scss` files are properly precompiled and there is no need to use `.erb` to the end of the files. I stand corrected, sorry. 

In any case I'm still unsure whether, as a matter of style, I wouldn't rather see the `.erb` at the end of the file, because at least in the beginning I was, like @masterkain, very puzzled by the failures caused by the `scss` files. But it does add an extra step to preprocessing, so I guess that we just have to keep it in our minds...?

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
