### ISSUE TITLE
PIE.htc issue

### ISSUE THREAD

**Issue by masterkain** [schneems/sprockets_better_errors#8]
I have this in code:

```
$pie-behavior: stylesheet-url("PIE.htc");
```

```
Asset depends on 'PIE.htc.css' to generate properly but has not declared the dependency
Please add: `//= depend_on_asset "PIE.htc.css"`
```

Not sure why it wants a `.css` extension.

**Comment by schneems** [comment]
Maybe stylesheet-url automatically appends a CSS here? Does the backtrace point at that line? You shouldn't be getting errors unless you're using erb in your code

**Comment by masterkain** [comment]
probably correct
